// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Football Tracker API Support",
            "email": "support@football-tracker.com"
        },
        "license": {
            "name": "Proprietary",
            "url": "#"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates user and returns session token in cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login with credentials",
                "parameters": [
                    {
                        "description": "Login credentials (email or username)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/football-tracker_internal_models_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful, session token set in cookie",
                        "schema": {
                            "$ref": "#/definitions/football-tracker_internal_models_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Invalidates user session and clears session cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Creates a new user account with username, email, and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/football-tracker_internal_models_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/football-tracker_internal_models_dto.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/championships": {
            "get": {
                "description": "Retrieves a list of all available football championships (FIFA World Cup, UEFA Euro, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Championships"
                ],
                "summary": "Get all championships",
                "responses": {
                    "200": {
                        "description": "List of championships",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/championships/{id}": {
            "get": {
                "description": "Retrieves detailed information about a specific championship",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Championships"
                ],
                "summary": "Get championship by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Championship ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Championship details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid championship ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/matches": {
            "get": {
                "description": "Retrieves all matches for a specific championship",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Get matches by championship",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Championship ID",
                        "name": "championshipId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of matches",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing or invalid championshipId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/matches/{id}": {
            "get": {
                "description": "Retrieves detailed information about a specific match",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Get match by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Match details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid match ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/predictions": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a prediction for a specific match. User must be authenticated. Only one prediction per match is allowed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Predictions"
                ],
                "summary": "Create a new prediction",
                "parameters": [
                    {
                        "description": "Prediction data",
                        "name": "prediction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/football-tracker_internal_models_dto.CreatePredictionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Prediction created successfully",
                        "schema": {
                            "$ref": "#/definitions/football-tracker_internal_models_dto.PredictionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or business logic error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "User not authenticated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/teams": {
            "get": {
                "description": "Retrieves all teams participating in a specific championship",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get teams by championship",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Championship ID",
                        "name": "championshipId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of teams",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing or invalid championshipId",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/teams/{id}": {
            "get": {
                "description": "Retrieves detailed information about a specific team",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get team by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Team details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid team ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "football-tracker_internal_models_dto.CreatePredictionRequest": {
            "type": "object",
            "required": [
                "away_score_regular",
                "home_score_regular",
                "match_id"
            ],
            "properties": {
                "away_score_regular": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1
                },
                "away_score_total": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2
                },
                "home_score_regular": {
                    "description": "Regular time prediction (required for all matches)",
                    "type": "integer",
                    "minimum": 0,
                    "example": 2
                },
                "home_score_total": {
                    "description": "Total score prediction (optional, for playoff matches)",
                    "type": "integer",
                    "minimum": 0,
                    "example": 3
                },
                "match_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "penalty_winner_team_id": {
                    "description": "Penalty shootout winner prediction (optional, for playoff matches)",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                }
            }
        },
        "football-tracker_internal_models_dto.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "description": "Can be username or email",
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePass123!"
                }
            }
        },
        "football-tracker_internal_models_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "For future JWT implementation",
                    "type": "string",
                    "example": "session_token_abc123"
                },
                "user": {
                    "$ref": "#/definitions/football-tracker_internal_models_dto.UserDTO"
                }
            }
        },
        "football-tracker_internal_models_dto.PredictionResponse": {
            "type": "object",
            "properties": {
                "away_score_regular": {
                    "type": "integer",
                    "example": 1
                },
                "away_score_total": {
                    "type": "integer",
                    "example": 2
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "home_score_regular": {
                    "description": "Regular time prediction",
                    "type": "integer",
                    "example": 2
                },
                "home_score_total": {
                    "description": "Total score prediction (optional)",
                    "type": "integer",
                    "example": 3
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "match_id": {
                    "type": "integer",
                    "example": 1
                },
                "penalty_winner_team_id": {
                    "description": "Penalty shootout winner prediction (optional)",
                    "type": "integer",
                    "example": 1
                },
                "points": {
                    "type": "integer",
                    "example": 3
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "user_id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "football-tracker_internal_models_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "SecurePass123!"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "john_doe"
                }
            }
        },
        "football-tracker_internal_models_dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "For future JWT implementation",
                    "type": "string",
                    "example": "session_token_abc123"
                },
                "user": {
                    "$ref": "#/definitions/football-tracker_internal_models_dto.UserDTO"
                }
            }
        },
        "football-tracker_internal_models_dto.UserDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Session token obtained from /api/v1/auth/login endpoint. After successful login, this cookie is automatically set.",
            "type": "apiKey",
            "name": "session_token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "Football Tracker API",
	Description:      "REST API for tracking football championships, matches, and user predictions. Supports multi-championship tracking with user prediction system, rating, and leaderboard functionality.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
