services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: football_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./migrations:/docker-entrypoint-initdb.d
    networks:
      - football_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Football Tracker Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football_tracker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=postgres  # Override localhost with postgres service name for Docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - football_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthCheck"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

volumes:
  postgres_data:

networks:
  football_network:
    driver: bridge
